### ISSUE TITLE
Need suggestion on how to convert my autocad building floor plan drawings that has asset numbers on it

### ISSUE THREAD

**Issue by infiavinash** [supipd/dxf2tbl2svg#1]
Need suggestion on how to convert my autocad building floor plan drawings that has asset numbers on it, to SVG format for use on the web and still be able to read those asset numbers off of SVG file?

**Comment by supipd** [comment]
infiavinash, general suggestion can be found on other places. If you have some problem with dxf2tblsvg, comment it more precisly.
